### ISSUE TITLE
Usage/Reports config errors: usageDatabase vs. usageDatabaseName 

### ISSUE THREAD

**Issue by remocrevo** [Coral-erm/Coral#221] opened 2017-05-25 11:44 UTC
Hi all,

I've been doing a few installs of Release Candidate 1 and I think there is a problem with the way the configuration files for either usage or reports or both are being populated. On the other hand I may just be doing things wrong!

So this is what I've found in reports/admin/configuration_sample.ini we have the line:

usageDatabase = ""

However when running the installer this line is generated in configuration.ini:

usageDatabaseName = "my_database"

The upshot of this is that the reports module fails to connect to the usage database. 
In /usage/admin/configuration.ini when running the installer this line is created:

usageDatabaseName = "my_database"

If you edit both configuration files to include:

usageDatabase = "my_database"

The reports module works properly.

cheers
Jon

Jon McGowan

**Comment by remocrevo** [comment] 2017-05-25 11:47
Note: This sounds like it was caused by the change in issue #188 and pull request #186 (the commit from March 8).

**Comment by jcuenod** [comment] 2017-05-25 20:53
Hi @remocrevo that was my immediate thought yes - I realise that I haven't updated any of those sample config files.
I thought I had caught all the instances of `usageDatabase` and updated them (in https://github.com/Coral-erm/Coral/commit/d6f47524de274609036574d5b9ad056a3b17ac0f) - could you tell me more specifically where things are going wrong?

**Comment by remocrevo** [comment] 2017-05-25 21:14
@jcuenod Sorry for the confusion, I was just posting a question that was mentioned on the email list. Also, it looks like @t4k found the problem and solved it in #222.

**Comment by remocrevo** [comment] 2017-05-25 21:17
Note: The original post from Jon says he fixed it by changing both the usage and reports config files to say "usageDatabase". @t4k Any idea why that would work also? Any chance your change is backwards from what we need?

**Comment by t4k** [comment] 2017-05-26 15:56
I didn’t actually get around to testing it or trying to reproduce the error, sorry about that.

For the pull request, I just looked at the changes in #186 related to `usageDatabase` and every instance of that string had things going from  `usageDatabase` to `usageDatabaseName`. I did a search in the current codebase and the only instance of `usageDatabase` left was in that sample config file.

I just kind of figured it would work by fixing the mismatch.

**Comment by jcuenod** [comment] 2017-05-26 16:48
Okay just to note, the change _to_ `usageDatabaseName` was intentional because it was normalising the terminology (the format `module` + `DatabaseName` is kind of standard). I think it would be better to figure out why the bug is happening than to go back. It doesn't seem as though @t4k's commit would have solved this though.

**Comment by t4k** [comment] 2017-05-31 16:49
I’m trying to reproduce the error now and having difficulty. I will post on the list for more information from the original reporter.

**Comment by jonmcgowan** [comment] 2017-06-01 09:00
Hi - I originally reported this issue - I'll grab master and run through a fresh install this morning and record the stages.

**Comment by jonmcgowan** [comment] 2017-06-01 09:53
I'm feeling very stupid now - having finished this install I see that problem I was seeing was due to a lack of data in the usage module. Sorry to have wasted peoples time.

**Comment by t4k** [comment] 2017-06-02 17:01
I’m going to close this issue since the original reporter (@jonmcgowan) says it is no longer an issue. This should let us release 2.0.0!

**Closed by t4k** 2017-06-02 17:01 UTC
Labels: bug
