### ISSUE TITLE
CORAL 3.0 bad query failure for Calendar in the Licensing Module

### ISSUE THREAD

**Issue by xsong9** [coral-erm/coral#461] opened 2018-07-27 17:20 UTC
CORAL user reported the calendar in the Licensing module does not work. After clicking on the Calendar tab, there is a message "Bad Query Failure" appears. I was able to reproduce the error on CORAL demo site and on another CORAL instance.

**Comment by jeffnm** [comment] 2018-07-31 14:58
I can confirm this is happening in our instance of 3.0 as well. I haven't investigated further to determine the cause.

**Comment by jeffnm** [comment] 2018-10-23 21:40
It comes from this line:
https://github.com/coral-erm/coral/blob/331c67082079e52777c53065235ddb8a1b8e840d/licensing/calendar.php#L115

When retrieving the mysqli_error we get 
`Unknown column 'coral_resources_prod.ResourceLicenseLink.resourceID' in 'on clause'`

The table was changed in 3.0.0
https://github.com/coral-erm/coral/blob/331c67082079e52777c53065235ddb8a1b8e840d/resources/install/protected/3.0.0/002-350.sql#L52

I think the solution will be to update the `calendar.php` to query the correct column names. `resourceAcquisitionID` instead of `resourceID`

**Comment by poacherone** [comment] 2018-10-24 13:18
It seems that this PR works as intended. I.e. it doesn't say Bad Query Failure anymore. How the calendar actually works, I have no idea. (Other that "Upcoming License Renewals" there is no data displayed, and I can't find any documentation on how the calendar is set-up.)

**Comment by jeffnm** [comment] 2018-10-24 16:46
A fix has been merged and will be included in the next release.

**Comment by jeffnm** [comment] 2018-10-25 20:53
The bad query was fixed by the changes in #505 but I messed up the fact that the order dates moved to the ResourceAcquisition table. That means you'll only get results with the current code if your DB has dates in the Resource table still.

**Comment by keelyward** [comment] 2018-11-12 17:37
I can also confirm this is also happening on our system.

**Comment by nkuitse** [comment] 2018-11-15 19:44
@jeffnm -- I don't understand your last comment.  Is there another bug?

> The bad query was fixed by the changes in #505 but I messed up the fact that the order dates moved to the ResourceAcquisition table. That means you'll only get results with the current code if your DB has dates in the Resource table still.

**Comment by jeffnm** [comment] 2018-11-28 14:32
@nkuitse yes, it's a different but related bug, the calendar display looks for the order dates in the Resource table, which is where they were previously. They have now been moved to the ResourceAcquisition table, so as it stands the licensing calendar won't to give any output for new installations.
https://github.com/coral-erm/coral/blob/76a434d7698043c9ca8aa829cdd63f6118f77a5d/licensing/calendar.php#L53

**Closed** 2019-01-08 17:14 UTC
Labels: bug
