### ISSUE TITLE
Links should not be capitalized

### ISSUE THREAD

**Issue by veggiematts** [coral-erm/coral#369] opened 2018-03-12 14:57 UTC
Many links in Coral are capitalized, like this one:

> Add New Resource Type

This is done through the following CSS rule:

`text-transform: capitalize;`

Capitalizing is not a correct grammar rule in many languages.
We should not enable it by default for every language.

**Comment by PaulPoulain** [comment] 2018-03-16 09:44
linked to #380

**Comment by jeffnm** [comment] 2018-03-22 21:26
I'm not sure this is a bug.

Isn't capitalization of links a style choice, not a grammar issue? It is sometimes referred to as Title Case, since most titles are capitalized in that manner. But I don't think it's a grammar issue in English, at any rate, any more than using ALL CAPS, which would be frowned upon for style reasons, but which is not a grammatical issue. 

I'm fine with us deciding that we want to change that style choice, if that's what we actually want to do.  #371 looks like it does that well. 

I'd be more convinced that this is a bug if non-latin scripts have problems with `text-transform: capitalize;`. I'll of course defer to the localization experts on this if it's an issue, I'd just like to understand why a little better.

**Comment by PaulPoulain** [comment] 2018-03-23 08:02
I strongly disagree: in French, this is a bug (and same thing in German, dunno for other languages, but I suspect Italians & Spanish ppl would say the same thing) : it's not good French to see "Ajouter Une Nouvelle Organisation".

So, if the English version must have a capitalized 1st letter for every word, then the strings must be capitalized in English, that must not be done through CSS, but in the code. Thus, localized version can be as they have to be.

BTW, closing this issue, as it's a duplicate of #371

**Comment by PaulPoulain** [comment] 2018-03-23 08:54
sorry, I was confused between issue & PR...

**Comment by PaulPoulain** [comment] 2018-03-23 14:50
Jeffrey,
the translation of the highlited terms with capitalization would be:
  * Nouvelle Ressource
  * Budgets
  * Ajouter Nouvel Utilisateur
=> for sure Ajouter Nouvel Utilisateur is strange for a frenchie.
Having a capital letter for the 1st word is normal, so Budget is OK.
The "Nouvelle Ressource" is harder to decide: the N is OK. The R is 
acceptable because it's a common name, and the "main object"/"major 
term", so you point this fact by capitalizing the 1st letter. But that's 
not a real/official rule.
So, for example : "Ajouter Ressource parente" (Add Parent Ressource) 
would be acceptable, as  "Ajouter ressource parente" would be as well.

In the 3rd example : "Ajouter nouvel Utilisateur" could be acceptable, 
"Ajouter nouvel utilisateur" as well. But not "Ajouter Nouvel Utilisateur".

At the end, the easiest & more consistent option in French is to 
capitalize only the 1st letter of the sentence, so:
"Nouvelle ressource", "Budgets", "Ajouter nouvel utilisateur"

[btw, the 3rd example is funny, because I think we should not write "Add 
New User", because we rarely "Add Already Existing User". So that should 
be "Add User" :D [I've open an issue about that too ;) ]

-- 
Paul Poulain, Associé-gérant / co-owner
BibLibre, Services en logiciels libres pour les bibliothèques
BibLibre, Open Source software and services for libraries

**Closed** 2018-04-05 13:16 UTC
Labels: bug
