### ISSUE TITLE
Resource accounts tab is not displayed anymore

### ISSUE THREAD

**Issue by veggiematts** [coral-erm/coral#439] opened 2018-06-19 14:52 UTC
Clicking on "Accounts" in the resource menu makes the menu and the tab content disappear. Caused by PR #424 ?

**Comment by jeffnm** [comment] 2018-06-19 15:11
I can reproduce the issue, but interestingly if I change the capitalization back to 'accounts' in the `directory.php` file, the accounts menu entry disappears. I think the Accounts menu entry is actually not needed for Resources. It's not displayed in 2.0.1 on our production server. 

Does anyone know what the Accounts menu item was originally intended for? If it's not needed here, we can remove it.

**Comment by jeffnm** [comment] 2018-06-21 13:30
Two alternative solutions: #441 Remove the Accounts menu entry or #443 Restore the Accounts menu entry.

When one is selected and merged, we can close this PR, merge #442 translations, and then release 3.0.

**Comment by techsvcslib** [comment] 2018-06-21 15:04
It took me a little while to understand what is going on here. If I understand correctly, this refers to the accounts vertical tab when looking at an individual resource record. To confirm: this is indeed important functionality and must be fixed.

**Comment by jeffnm** [comment] 2018-06-21 15:20
Merged #443

**Closed by jeffnm** 2018-06-21 15:20 UTC
Labels: bug, release blocking
