### ISSUE TITLE
Installer failingat resrouces module for 3.0 upgrade

### ISSUE THREAD

**Issue by bmenk** [coral-erm/coral#468] opened 2018-08-22 13:36 UTC
Trying to upgrade from 2.x to 3.0 on RHEL 7 linux, php 5.6.25, mariadb 5.5.56. Databases are the set from our current 2.x instance. Downloaded Coral-3.0.0.zip, unpacked it in dir /var/www/html/coral. Copied in the module configuration.ini files from 2.x instance. Went to [hostname]/coral/ to start things. All looks normal till it gets to the resources module when it breaks as it tries to insert tables & columns into the database. See screen snap for exact errors. Can you advise me on how to get past this?   This is very similar to issues I had going from 1.x to 2.x when I was referred by Jason Raitz to this issue: https://github.com/coral-erm/coral/pull/290 - has that not been fixed or is this perhaps something else? 

Thanks - Bobb Menk, MIT Lincoln Laboratory Library

![clipboard01](https://user-images.githubusercontent.com/42610857/44466371-21a41100-a5ee-11e8-8d70-ab643bfd5d94.jpg)

**Comment by jeffnm** [comment] 2018-08-22 13:52
When you copied the configuration.ini files, did you copy the `common/configuration.ini` file as well as the module ones? If not, the installer is probably trying to upgrade from 1.x rather than 2.0. 

#290 was merged and also only effects one column, not the many duplicates columns you are seeing, so that probably isn't the issue. The SQL statements in the error messages are all 2.0 upgrade SQL changes, not 3.0 upgrades. 
 
It might be easier to copy your whole 2.0 directory into your `/var/www/html/coral` then copy the contents of your 3.0 download into `/var/www/html/coral`. The configuration files will not be overwritten because they don't exist in the repository.

**Comment by bmenk** [comment] 2018-08-22 14:00
Thanks for getting back to me on this so quickly.

 

This upgrade has been very odd in many ways – I can detail some of the larger issues I’ve seen after I get it to work if you’re interested. 

 

So you’re saying I can do an unzip of Coral 3 using the overwrite option on top of an existing Coral 2 instance? 

 

Bobb

**Comment by bmenk** [comment] 2018-08-22 14:59
I blew away the instance that was giving me trouble. Copied in a fresh copy from our 2.0 instance. Dropped all the db's and re-imported from dumps to make sure they were all clean. Unpacked the 3.0 zipfile in it's own dir. Copied with overwrite into the 2.0 instance. Started the upgrader.

It did the common and resources upgrades, said "all done". I let it do it's re-direct, at which point it went into upgrade mode again and did the rest of the modules.

I logged in as admin.  Licensing, Organizations, Usage, all work as expected. Resources opens, but never displays any records. I'm getting an endless "processing" spinner (see screen snap). I told resources/index.php to display errors, and reloaded the page. No errors same spinner, no records.

Seems like Resources module didn't completely upgrade perhaps? Or at least did something differently than the other modules did during upgrade. What do you suggest?

Thanks. Bobb

![image](https://user-images.githubusercontent.com/42610857/44471700-7483c580-a5fa-11e8-99f4-a5d9d84cac00.png)

**Comment by bmenk** [comment] 2018-08-22 16:28
Here's what we came up with to fix this:
In <coral>/resources/admin/configuration.ini we had the defaultsort key as this: 
"TRIM(LEADING \'THE \' FROM UPPER(R.titleText)) asc" 
...and the single-quote escapes were not only unnecessary but fatal

**Comment by bmenk** [comment] 2018-08-22 19:00
It seems that the upgrader itself is re-writing this value in the file so that it reads: "TRIM(LEADING \'THE \' FROM UPPER(R.titleText)) asc" . I double checked that value before running the upgrade and it did not have those escaping slashes. But they were there afterwards and they did keep the Resources module from loading properly as noted above.

**Comment by bmenk** [comment] 2018-08-22 19:08
So having done one more completely clean install: deleted the entire v3.0 coral directory structure, copied the directory structure fresh from 2.0 instance, dropped the db's, and then imported the data from current v2.0 mysql dumps, copied the zip contents into the v 2.0 dir using overwrite option, ran the upgrader, here's where things stand: I can use the application, but when I try to export search results from Resources to Excel it breaks. The error I'm seeing is below, but it indicates that for some reason there is at least one missing field in the mysql db. Could we run the sql files that do the db structure changes manually? If so where do they live?
Thanks. 
Bobb Menk

Fatal error: Uncaught exception 'Exception' with message 'There was a problem with the database: Unknown column 'RPAY.priceTaxExcluded' in 'field list'' in /var/www/html/coral/resources/admin/classes/common/DBService.php:52 Stack trace: #0 /var/www/html/coral/resources/admin/classes/common/DBService.php(91): DBService->checkForError() #1 /var/www/html/coral/resources/admin/classes/domain/Resource.php(1058): DBService->processQuery('SELECT R.resour...', 'assoc') #2 /var/www/html/coral/resources/export.php(46): Resource->export(Array, 'TRIM(LEADING 'T...') #3 {main} thrown in /var/www/html/coral/resources/admin/classes/common/DBService.php on line 52

**Comment by jeffnm** [comment] 2018-08-22 19:17
Looks like you found a bug! I can reproduce that fatal error when attempting to export a search result.  We can open a new Issue for it.

**Comment by weberc** [comment] 2018-09-04 11:05
I also have the issue with the empty resources module.
Checking the database scheme, it looks like it never got updated to the new 3.0 scheme during upgrading process.
Seems like the script `coral/resources/install/protected/3.0.0/002-350.sql` never ran during upgrade.
The table ResourceAcquisition never got created and some deleted columns from table Resource still exist.

**Closed** 2023-03-08 15:58 UTC
