### ISSUE TITLE
Subscription dates not set correctly for orders during upgrade

### ISSUE THREAD

**Issue by poacherone** [coral-erm/coral#489] opened 2018-09-28 11:59 UTC
When upgrading to Coral 3.0.0 from 2.0.1 the upgrade script doesn’t migrate all the Acquisitions data to the new ResourceAcquisitions table. The columns currentStartDate and currentEndDate are kept in the Resource table while all newly created orders are instead given today’s date in both subscriptionStartDate and subscriptionEndDate (“NOW()” on line 100 in the [upgrade SQL](https://github.com/coral-erm/coral/blob/master/resources/install/protected/3.0.0/002-350.sql)).

As far as we can tell there is no way to access/edit currentStartDate or currentEndDate from the UI in 3.0.0., and the newly created orders have incorrect dates. We believe this to be a bug. 

Preferably the dates from currentStartDate/EndDate should be migrated like the other Acquisition/Order data during the upgrade (to subscriptionStartDate/EndDate), and then drop the columns from Resource.

**Comment by veggiematts** [comment] 2018-10-11 13:54
After doing some digging, it feels like a bug to me too.
However, I'd like a second opinion on this.
In any case, if it is a bug, it should be fixed for 3.0.1

**Comment by veggiematts** [comment] 2018-10-11 14:17
Proposal:
  - update each first resourceAcquisition (ie: the one created by default during the 3.0 upgrade) with the dates of the matching resource
  - remove all remaining occurrences of the resource dates in the code.
  - drop the dates columns for the resource table.

**Comment by poacherone** [comment] 2018-10-24 09:22
I agree with @veggiematts proposal, it makes sense. This issue would really need to be fixed for Coral 3.0.1 I think, since ALL orders will have the wrong subscription dates without it.

**Comment by jeffnm** [comment] 2018-10-24 13:17
@veggiematts your proposal sounds good to me as well. The Resource table's currentStartDate and currentEndDate are currently still present in a 3.0.0 fresh installation as well, since we opted to change the install method to run the upgrades in sequence rather than updating the install.sql file every time we do a new release.

**Comment by veggiematts** [comment] 2018-10-24 14:35
There are two problems with this proposal though:
  1. I'm not sure how to update only the first ResourceAcquisition with a SQL query only (and we cannot use php scripts to update the database)
  2. If some users did modify the default order, their modification will be discarded.

**Comment by jeffnm** [comment] 2018-10-24 15:22
I think we could update the ResourceAcquisitions by looking for Resource Dates that are not null with a matching resourceID. Anything that was created afterwards will have null in those values.  

You are right, if someone edited ResourceAcquisition values they would be overwritten. There's not really anyway to know when now() was used, unless normal users don't set the exact same time in both subscriptionStartDate and subscriptionEndDate. If that's the case, we might be able to check that those two fields are identical before overwriting them with the corresponding currentStartDate and currentEndDate.

**Comment by veggiematts** [comment] 2018-10-25 08:13
@jeffnm yep, good points. Are you willing to do this? If you do it, I'll test it :)

**Comment by poacherone** [comment] 2018-10-25 08:49
The comments from @jeffnm makes sense to me too. But, there are some (small?) issues. Since people could have updated to 3.0.0 and started working in production, they might have added more orders (=more lines in ResourceAcquisitions referencing the same resourceID). Would these new orders have their dates overwritten by the dates from currentStartDate/currentEndDate?

Also, the problem of [issue 478](https://github.com/coral-erm/coral/issues/478), which sets both subscriptionStartDate and subscriptionEndDate as now() as default, which might make looking at the exact time difficult.But, I would guess that people actually in production aren't using the default dates, so this might not be an actual problem but rather a hypothetical one.

If there is a PR created for this one, I can test too!

**Comment by veggiematts** [comment] 2018-10-25 08:58
I also added this as release blocking, if you're okay with that @jeffnm . The sooner we fix this the better.

**Comment by jeffnm** [comment] 2018-10-25 16:59
@poacherone and @veggiematts How about this update statement?

```
UPDATE ResourceAcquisition RA
JOIN Resource R ON R.resourceID = RA.resourceID
SET
RA.subscriptionStartDate=R.currentStartDate,
RA.subscriptionEndDate=R.currentEndDate
WHERE
((R.currentStartDate IS NOT NULL) AND (R.currentStartDate != "0000-00-00")
  OR (R.currentEndDate IS NOT NULL) AND (R.currentEndDate != "0000-00-00"))
AND R.currentStartDate != R.currentEndDate
AND RA.subscriptionStartDate = RA.subscriptionEndDate;
```

If a resource has multiple orders with begin and end dates that are the same (within the order), they will all get the old dates from currentStartDate and currentEndDate. I'm not sure how to differentiate intentionally created order start and end dates that have the exact same date and those that were generated by the default or during the 3.0.0 upgrade. However, they will only be updated if there is a more reliable looking date in the Resource table. I'm hoping most people will have manually set begin and end dates on new orders, even if they have ignored the old ones.

I'm not sure what PHP changes are needed yet, so no PR just yet.

**Comment by poacherone** [comment] 2018-10-25 20:28
That update statement should do the trick. I tried it on a test server and it looks correct to me, after a brief overview. I'll have to look more closely to make sure though...

One thing though, I had to comment out the (R.currentStart/EndDate != "0000-00-00") part, to get the SQL query to run. Got an error about time format.

**Comment by veggiematts** [comment] 2018-10-26 09:14
I tested the update statement, it did the trick.
I didn't have to remove the (R.currentStart/EndDate != "0000-00-00") part (10.0.36-MariaDB)
@poacherone what's your mysql/mariadb version?

**Comment by poacherone** [comment] 2018-10-26 09:19
I have MySQL 5.7.24 on the test server.

**Comment by poacherone** [comment] 2018-10-26 13:18
We have now looked some more at our updated data. We have several resources where either currentStartDate or currentEndDate is NULL and it looks like they haven't been updated. But looking at the SQL statement, I would expect them to update. Could it be because subscriptionStartDate and subscriptionEndDate cannot be NULL in the database?

**Comment by poacherone** [comment] 2018-10-26 13:28
Sorry, wasn't clear. subcriptionStartDate and subscriptionEndDatearen't updated if there is NULL in either currentStartDate or currentEndDate. Trying to figure out why.

**Comment by veggiematts** [comment] 2018-10-26 13:39
Please note that subcriptionStartDate and subscriptionEndDate will be NULLable if #509 is merged.

**Comment by jeffnm** [comment] 2018-10-26 14:28
@poacherone do you mean that one Resource record has a currentStartDate that is a date and a currentEndDate that is NULL, and the ResourceAcquisition table doesn't get either subscriptionStartDate or subscriptionEndDate updated?  

In that case you'd expect the date from currentStartDate to end up in subscriptionStartDate, even if the NULL can't be copied to subscriptionEndDate? 

The problem is that I compared `R.currentStartDate != R.currentEndDate` and any NULL values cause the whole comparison to return NULL which evaluates false. 

As an example of this behavior:
Try `SELECT * FROM Resource WHERE (currentStartDate IS NULL OR currentEndDate IS NULL);` That will load  all your null columns.  
Try `SELECT * FROM Resource WHERE (currentStartDate IS NULL OR currentEndDate IS NULL) AND currentStartDate <> currentEndDate;`
You will get nothing back, even though you would expect to get rows that have NULL in one column, but the two columns don't contain the same value. However, because of how NULL is evaluated, it will always result in that clause being false, meaning it's impossible for both the first clause and the second clause to both be true. 

I think the following will work. I've tested it with a date in currentStartDate and null in currentEndDate and it puts the date in subscriptionStartDate and 0000-00-00 in subscriptionEndDate (because my DB still doesn't allow NULL on that column, but it would be NULL after #509 is merged and applied.)

```
UPDATE ResourceAcquisition RA
JOIN Resource R ON R.resourceID = RA.resourceID
SET
RA.subscriptionStartDate=R.currentStartDate,
RA.subscriptionEndDate=R.currentEndDate
WHERE
(((R.currentStartDate IS NOT NULL) AND (R.currentStartDate <> "0000-00-00"))
  OR ((R.currentEndDate IS NOT NULL) AND (R.currentEndDate <> "0000-00-00")))
AND (R.currentStartDate != R.currentEndDate
  OR (R.currentStartDate IS NULL OR R.currentEndDate IS NULL))
AND RA.subscriptionStartDate = RA.subscriptionEndDate;
```
This will still leave NULL NULL Resources alone, which I think is probably the right choice.
The first WHERE clause requires at least one non-NULL or non-0000-00-00 date in one of the two columns. The second says they can't be the same date, or one of the columns needs to be null (obviously, if both are null, then the previous clause is false and the row is ignored). 
The third clause says that we only do this for ResourceAcquisition records that have the same date in both start and end fields.

**Comment by poacherone** [comment] 2018-10-26 17:14
@jeffnm yes, that is exactly the behavior I envisioned. I tried your query (taking away the "0000-00-00" since my version of MySQL complains about that), and it works brilliantly! Nice work!

I agree that it makes sense to leave NULL NULL Resources alone. At least in our data, they are almost always tests, if they exist at all.

**Comment by veggiematts** [comment] 2018-10-29 10:44
Should I make a pull request out of this?

**Comment by jeffnm** [comment] 2018-10-29 14:58
I've opened one - #510.

I'm having second thoughts about dropping the currentStartDate and currentEndDate columns. I know we tell people to back up their database before doing updates, but I'm still concerned about deleting their data without a recovery option, especially since not every record is being copied over (due to the difficulty of knowing if the old data is better or worse than what's in the new table).

**Comment by poacherone** [comment] 2018-10-29 16:18
I'll take a look at the PR when I get a chance, probably tomorrow. But just wanted to comment on dropping the columns. Although I'm not to keen to keep unused columns/data in general, in this case it might be a good idea to keep, since not all the data will be migrated to the new table.

**Comment by jeffnm** [comment] 2019-01-08 16:53
A fix has been merged and will be included in the next release.

**Closed by jeffnm** 2019-01-08 16:53 UTC
Labels: bug
