### ISSUE TITLE
Enhancements to the import tool

### ISSUE THREAD

**Issue by veggiematts** [coral-erm/coral#8] opened 2016-03-14 13:43 UTC
Currently, the import tool allows the user to map only a few fields from the Resource table to CSV columns.

My proposal is to increase the number of fields available in step 2 of the import tool, so the user can map any field of the Resource table. 

For convenience, if a CSV column fit the MySQL database name, then the link will be automatically made and proposed by default.

**Comment by cjc66** [comment] 2016-03-30 23:38
SirsiDynix has done some work on this, please take a look at the attached document.
[Import updates.docx](https://github.com/Coral-erm/Coral/files/196752/Import.updates.docx)

**Comment by veggiematts** [comment] 2016-03-31 13:10
Is there a pull request for this ?

**Comment by cjc66** [comment] 2016-03-31 15:33
Not yet, we are still testing internally, but will probably do so in the next few days.

CARLA CLARK, MLIS | Product Manager | SirsiDynix
Carla.Clark@SirsiDynix.com<mailto:Carla.Clark@SirsiDynix.com>
P:  801.223. 5734 | M: 318.401.0606
TOLL FREE: 800. 288.8020 x5734
www.SirsiDynix.com<http://www.sirsidynix.com/>

**Comment by ehartnett** [comment] 2016-03-31 19:36
Can I suggest that you take into account for the fact that the file might have headers?

**Comment by fondrenlibrary** [comment] 2016-03-31 21:58
it's a nice add-on yet  counting and recording field orders  is a little bit error prone. It could be  a plus if a user can load a couple of  rows from a training sample CSV and then let user interactively  assign and map fields.

**Comment by techsvcslib** [comment] 2016-03-31 22:24
This is something I articulated to NCSU folks as desirable: the ability to preview results of initial mapping and allow the user to then adjust as needed and try again.

Steve

**Comment by benheet** [comment] 2016-04-01 15:04
+1 from me for a preview of what the results will look like before the upload completes. That feature to preview has worked well for the statistics upload.

**Comment by benheet** [comment] 2016-04-01 15:08
I'd like to see this in action. I'm interested in the dedupe checkbox and how its working, and +1 to Eric's comment about headers. Perhaps adding a 'avoid x header rows' would be helpful OR require a standard header on your input file that the system always looks for and always ignores. 

Also, is there somewhere I can go to see the history of all my uploads. And what happens if I don't like the upload results, can I conveniently undo or delete or previous upload?

**Comment by xsong9** [comment] 2016-04-04 20:36
I like the idea of configuring an import template! We are also really interested in having the Acquisition Type filed mapped as well. I don't see this field in the document. Can this be added? The desired outcome will be when resources are imported, a corresponding workflow can be triggered if the controlling fields Acquisition Type and the Resource Format are filled in.

**Comment by PaulPoulain** [comment] 2016-04-06 12:31
My 2 cts: IMHO, when a new feature is submitted by a volunteer, there is always another way to do it, or an idea that would improve the feature. I think such suggestions CAN be taken into account by the submitter if he is willing to, but it should not be a pre-requisite to merge the feature if it work well. It should be in a separate issue.
Of course, this does not apply if the feature is buggy or unusable or defective by design.

I think that :
 * "Can I suggest that you take into account for the fact that the file might have headers?" => can almost be considered as a bug, because if a library submit a file with header, the behaviour could be wrong.
 * It could be a plus if a user can also load a couple of rows from a training sample CSV => for another issue
 * let user interactively assign and map fields.  => for another issue
 * the ability to preview results of initial mapping and allow the user to then adjust as needed and try again. => for another issue
 *

**Comment by benheet** [comment] 2016-04-06 12:45
The current governance rules require new features to be approved by the steering committee. The rules may however be changed by a majority vote of the steering committee if it is put forward for discussion.

**Comment by jeffnm** [comment] 2016-11-05 12:27
Did the steering committee ever discuss this? I'm afraid I don't remember, but it still has the SC review needed label.

**Comment by cjc66** [comment] 2016-11-08 23:51
Seems like we have talked about it quite a bit.  What is the current status of the enhancements that NCSU had outlined?

**Comment by xsong9** [comment] 2016-11-09 13:42
We are working on the development for the import tool enhancement now.  Here is what we proposed:
![coral import tool](https://cloud.githubusercontent.com/assets/10168937/20140256/36b61d5a-a658-11e6-837b-db0a8ccfc092.JPG)

We are doing testing now and will create a pull request in the next couple of weeks.

**Comment by benheet** [comment] 2016-11-16 16:16
I don't think any SC members are using the latest import feature, correct? If so we aren't in a good place to react to NCSU's proposal in this issue. There's no pull request yet so I think we should assume we aren't dealing with this until after v2.0. Carla, did you have work on the import feature that you delayed because NCSU was working on it or did you just want to find out if we were wanting to see more done on this for v.20 launch?

**Comment by techsvcslib** [comment] 2016-11-16 16:53
I’ve used the latest import tool (by which I assume you mean, the version contributed by BibLibre a year or more ago) and stopped using it almost immediately due to problems. I’ve been waiting to hear from NCSU on a pull request before doing anything further in terms of trying out their stuff.

Steve


On Nov 16, 2016, at 10:16 AM, benheet <notifications@github.com<mailto:notifications@github.com>> wrote:


I don't think any SC members are using the latest import feature, correct? If so we aren't in a good place to react to NCSU's proposal in this issue. There's no pull request yet so I think we should assume we aren't dealing with this until after v2.0. Carla, did you have work on the import feature that you delayed because NCSU was working on it or did you just want to find out if we were wanting to see more done on this for v.20 launch?

**Comment by cjc66** [comment] 2016-11-16 17:01
I just wanted to know where they are-we do not have any plans to do more work on the import feature.  I’m eager to see the final result!

-Carla

**Comment by cjc66** [comment] 2016-11-16 17:11
Steve, have you tried the updated import features that SirsiDynix built to see if it works for you?  Just curious.  We’ve been testing internally and several of our pilot sites have also tested, and while it could still use some enhancements (hopefully the NCSU work improves it even more) we have not seen any major issues.

-Carla

**Comment by techsvcslib** [comment] 2016-11-16 18:10
Apologies up front if I missed something but are those part of the master code yet, Carla? We are running ver. 1.4.1 in production and I just checked the import function there and don’t see your changes in place.

Steve


On Nov 16, 2016, at 11:11 AM, Carla Clark <notifications@github.com<mailto:notifications@github.com>> wrote:

Steve, have you tried the updated import features that SirsiDynix built to see if it works for you? Just curious. We’ve been testing internally and several of our pilot sites have also tested, and while it could still use some enhancements (hopefully the NCSU work improves it even more) we have not seen any major issues.

-Carla

**Comment by cjc66** [comment] 2016-11-16 19:05
Steve, our changes should be there.  Do you have the ability to create a template?  You can take a look at our test box here: https://erm.bc.sirsidynix.net/resources/

Login with test / ermuser

You should have the option in Resources/Admin to create an import configuration:

[cid:image003.jpg@01D24001.B51E9130]



If this is what yours looks like, and you abandoned it, then that’s ours that you walked away from ☺

…and hopefully the NCSU work will improve it further!

-Carla

**Comment by techsvcslib** [comment] 2016-11-16 19:26
Thanks, Carla. It’s strange that I can see and use the functionality you describe in your sandbox but in our production instance, apparently using the same version, I can’t. I’ll investigate further. Perhaps there is a configuration.ini setting that needs to be tweaked.

Steve

**Comment by benheet** [comment] 2016-11-16 19:29
I was referring to the import feature in version 2.0 that SirsiDynix provided.

**Comment by techsvcslib** [comment] 2016-11-16 19:46
OK, but the version shown in SirsiDynix’s sandbox and our production version are the same, thus my confusion.

Steve


On Nov 16, 2016, at 1:29 PM, benheet <notifications@github.com<mailto:notifications@github.com>> wrote:


I was referring to the import feature in version 2.0 that SirsiDynix provided.

**Comment by benheet** [comment] 2016-11-16 19:51
then i think we're good and what's there now is what is supposed to be there and we don't have any conflicts and we just now wait for ncsu to do there thing after 2.0 is launched.

**Comment by cjc66** [comment] 2016-11-16 20:49
Okay, good—yes, we are not doing anything new, just waiting for the NCSU work to be completed.

**Comment by xsong9** [comment] 2017-01-19 20:00
@cjc66 @ @techsvcslib @benheet We have completed the import tool development. Here are the three push requests:
https://github.com/Coral-erm/Coral/pull/154
https://github.com/Coral-erm/Coral/pull/153
https://github.com/Coral-erm/Coral/pull/152

Let me know if they can be merged into 2.0 beta. If so, I can have the documentation ready for the release. 
Thanks!

-- Yan

**Comment by jeffnm** [comment] 2017-01-24 16:07
I"m not sure why this was closed when I merged the unified installer. I don't think this has been resolved, so I'm reopening.

**Comment by xsong9** [comment] 2017-01-24 16:13
We have completed the development. Here are the three pull requests:
https://github.com/Coral-erm/Coral/pull/154
https://github.com/Coral-erm/Coral/pull/153
https://github.com/Coral-erm/Coral/pull/152

Let me know if you have any question.

**Comment by xsong9** [comment] 2017-09-08 18:47
We just migrated to CORAL 2.0 and we all love it here! 
The import tool enhancement is the only piece not merged yet. I read through all the related issues and it appears to me that all enhancements included in this request have been merged. @t4k Is that correct?

**Comment by t4k** [comment] 2017-09-08 20:49
@xsong9: Yes, it looks like all the cleanup work I did to the original PRs has been merged into the development branch. I have more fields to be added myself, and I will create new issues and PRs for those changes.

I believe this issue can be closed.

**Closed** 2017-10-05 20:48 UTC
Labels: enhancement, SC review needed
